# Generated by Django 3.1.1 on 2020-09-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='closed',
            new_name='completed',
        ),
    ]
