# Generated by Django 3.1.1 on 2020-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0002_auto_20200923_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
